# -*- coding: utf-8 -*-
"""Untitled65.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NRM33bGOCowPpU32LG5FIDugdHrKZXvA
"""

pip install gradio pandas matplotlib twilio python-dotenv

ACCOUNT_SID = "AC4d2878e18f81b0abe3a5e01217ec07ae"
AUTH_TOKEN = "7200bb8ebc6322e1db73973468ffa892"
TWILIO_NUMBER = "+15705219833"  # Your Twilio number

!pip install gradio pandas matplotlib twilio

import gradio as gr
import pandas as pd
import matplotlib.pyplot as plt
import sqlite3
from twilio.rest import Client
import os
ACCOUNT_SID = "AC4d2878e18f81b0abe3a5e01217ec07ae"
AUTH_TOKEN = "7200bb8ebc6322e1db73973468ffa892"
TWILIO_NUMBER = "+15705219833"
client = Client(ACCOUNT_SID, AUTH_TOKEN)

conn = sqlite3.connect("patients.db", check_same_thread=False)
cursor = conn.cursor()

cursor.execute("""
CREATE TABLE IF NOT EXISTS patients (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    Name TEXT,
    Age INTEGER,
    Blood_Pressure REAL,
    Temperature REAL,
    Mood TEXT,
    Bleeding TEXT,
    Pain_Level INTEGER,
    PPD_Symptom TEXT,
    Husband TEXT,
    Mother TEXT,
    Result TEXT,
    SMS_Status TEXT,
    Call_Status TEXT
)
""")
conn.commit()


def format_number(number):
    number = str(number).strip().replace(" ", "")
    if not number.startswith("+"):
        number = "+91" + number
    return number

def df_to_html_colored(df):
    html = '<table border=1 style="border-collapse: collapse; width: 100%;">'
    html += "<tr>" + "".join([f'<th style="padding:5px;background:#f2f2f2">{col}</th>' for col in df.columns]) + "</tr>"
    for _, row in df.iterrows():
        color = "#ffcccc" if "RISK" in row["Result"] else "#ccffcc"
        html += "<tr>"
        for item in row:
            html += f'<td style="padding:5px;background:{color}">{item}</td>'
        html += "</tr>"
    html += "</table>"
    return html

def send_sms(alert, husband, mother):
    sms_status = ""
    try:
        client.messages.create(body=alert, from_=TWILIO_NUMBER, to=husband)
        sms_status += f"✅ SMS sent to Husband ({husband}). "
    except Exception as e:
        sms_status += f"❌ SMS to Husband failed ({e}). "

    try:
        client.messages.create(body=alert, from_=TWILIO_NUMBER, to=mother)
        sms_status += f"✅ SMS sent to Mother ({mother}). "
    except Exception as e:
        sms_status += f"❌ SMS to Mother failed ({e}). "
    return sms_status

def make_call(alert, husband, mother):
    call_status = ""
    twiml = f"<Response><Say>{alert}</Say></Response>"
    try:
        client.calls.create(twiml=twiml, to=husband, from_=TWILIO_NUMBER)
        call_status += f"✅ Call initiated to Husband ({husband}). "
    except Exception as e:
        call_status += f"❌ Call to Husband failed ({e}). "

    try:
        client.calls.create(twiml=twiml, to=mother, from_=TWILIO_NUMBER)
        call_status += f"✅ Call initiated to Mother ({mother}). "
    except Exception as e:
        call_status += f"❌ Call to Mother failed ({e}). "
    return call_status

def check_health(name, age, bp, temp, mood, bleeding, pain, ppd, husband, mother):
    risk = False
    reason = ""

    if bp < 90 or bp > 140:
        risk = True
        reason += "Blood Pressure abnormal. "
    if temp > 38:
        risk = True
        reason += "High Temperature. "
    if mood.lower() in ["sad", "angry", "tired", "depressed", "irritable"]:
        risk = True
        reason += "Negative Mood. "
    if bleeding.lower() in ["moderate", "heavy"]:
        risk = True
        reason += "Bleeding issue. "
    if pain > 6:
        risk = True
        reason += "High Pain Level. "
    if ppd.lower() in ["moderate", "severe"]:
        risk = True
        reason += "PPD Symptoms present. "

    husband = format_number(husband)
    mother = format_number(mother)

    if risk:
        alert = f"🚨 Alert: Patient {name} is at RISK. {reason} Immediate check-up required."
        sms_status = send_sms(alert, husband, mother)
        call_status = make_call(alert, husband, mother)
        result = f"🚨 Patient {name} is at RISK. {reason}{sms_status}{call_status}"
    else:
        sms_status = "No SMS sent (Patient SAFE)"
        call_status = "No call made (Patient SAFE)"
        result = f"✅ Patient {name} is SAFE."

    cursor.execute("""
        INSERT INTO patients
        (Name, Age, Blood_Pressure, Temperature, Mood, Bleeding, Pain_Level, PPD_Symptom, Husband, Mother, Result, SMS_Status, Call_Status)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    """, (name, age, bp, temp, mood, bleeding, pain, ppd, husband, mother, result, sms_status, call_status))
    conn.commit()

    df_recent = pd.read_sql_query("SELECT * FROM patients ORDER BY id DESC LIMIT 10", conn)
    df_all = pd.read_sql_query("SELECT * FROM patients", conn)

    csv_file = os.path.join(os.getcwd(), "patients_report.csv")
    df_all.to_csv(csv_file, index=False)


    count_safe = df_all['Result'].str.contains("SAFE").sum()
    count_risk = df_all['Result'].str.contains("RISK").sum()
    chart_file = os.path.join(os.getcwd(), "chart.png")
    plt.figure(figsize=(4,3))
    plt.bar(["SAFE", "RISK"], [count_safe, count_risk], color=["green", "red"])
    plt.title("Postpartum Health Status Overview")
    plt.xlabel("Status")
    plt.ylabel("Number of Patients")
    plt.tight_layout()
    plt.savefig(chart_file)
    plt.close()

    html_table = df_to_html_colored(df_recent)
    return result, html_table, chart_file, csv_file

app = gr.Interface(
    fn=check_health,
    inputs=[
        gr.Textbox(label="Name"),
        gr.Number(label="Age"),
        gr.Number(label="Blood Pressure"),
        gr.Number(label="Temperature"),
        gr.Dropdown(["Happy","Sad","Angry","Tired","Depressed","Irritable"], label="Mood"),
        gr.Dropdown(["None","Mild","Moderate","Heavy"], label="Bleeding"),
        gr.Slider(0, 10, label="Pain Level"),
        gr.Dropdown(["Mild","Moderate","Severe"], label="PPD Symptom"),
        gr.Textbox(label="Husband Number", value="+91"),
        gr.Textbox(label="Mother Number", value="+91")
    ],
    outputs=[
        gr.Textbox(label="System Message"),
        gr.HTML(label="Recent Patient Records"),
        gr.Image(label="Health Risk Chart"),
        gr.File(label="⬇️ Download Full Patient Report")
    ],
    title="👩‍🍼 Postpartum Health Monitoring System (SQLite + CSV + Twilio)",
    description="Detects postpartum risk, sends real SMS & voice calls using Twilio, saves patient records in SQLite, shows risk chart, and allows CSV download."
)


app.launch(share=True)